version: 1.0.{build}
image: ubuntu

environment:
  DOCKER_USER:
    secure: grozlhrle
  DOCKER_PASS:
    secure: ${{ secrets.DOCKERHUB_TOKEN }}
install:
  - docker version

build_script:
  - docker build -t malpine ./scripts/cpu-mualpine

test_script:
  - docker run malpine
