# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- base
- dev

variables:
  imageNameAi: 'cpu-ai:$(build.buildId)'
  imageNamePython: 'cpu-python:$(build.buildId)'

jobs:
- job: BuildAndRun
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      CpuAi:
        contextPath: './scripts/cpu/cpu-ai'
        imageName: 'cpu-ai:$(build.buildId)'
      CpuPython:
        contextPath: './scripts/cpu/cpu-python'
        imageName: 'cpu-python:$(build.buildId)'
  steps:
    - script: |
        docker build -t $(imageName) $(contextPath)
      displayName: 'docker build'

    - script: |
        docker run $(imageName)
      displayName: 'docker run'