name: Run Codefresh Pipeline and Build Docker Image

on:
  push:
    branches:
      - main  # Trigger for running Codefresh pipelines
      - dev   # Trigger for building and pushing Docker images

jobs:
  codefresh:
    if: github.ref == 'refs/heads/main'  # Only run on the main branch
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Use the latest version of checkout action

      - name: 'Run Pipeline: idie/idie'
        uses: codefresh-io/codefresh-pipeline-runner@v6
        env:
          PIPELINE_NAME: 'idie/idie'
          TRIGGER_NAME: 'grozlhrle/idie'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}  # Use repository secrets for sensitive data
        id: run-pipeline

      - name: 'Run Pipeline: default/MyPipeline'
        uses: codefresh-io/codefresh-pipeline-runner@v6
        env:
          PIPELINE_NAME: 'default/MyPipeline'
          TRIGGER_NAME: 'grozlhrle/idie'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}  # Use repository secrets for sensitive data
        id: run-pipeline1

  docker:
    if: github.ref == 'refs/heads/dev'  # Only run on the dev branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Use the latest version of checkout action

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2  # Use the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Use the latest version

      - name: Login to DockerHub
        uses: docker/login-action@v2  # Use the latest version
        with:
          username: grozlhrle
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use repository secrets for sensitive data

      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # Use the latest version
        with:
          context: ./scripts/cpu
          file: ./scripts/cpu/Dockerfile
          platforms: linux/amd64,linux/386
          push: true
          tags: grozlhrle/idie:latest